config/routes.rb
Rails.application.routes.draw do
  
  root 'users#top'
  get 'renovation', to: 'users#renovation'
  get 'users_wing', to: 'users#wing'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :acount_activations, only: [:edit]
  resources :password_resets, only: [:new , :create, :edit, :update]
 
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                 BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)                                             
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(attrbute, token)
    digest = send("#{attrbute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end
  
  def send_activation_email
    mail = UserMailer.acount_activation(self)
    mail.transport_encoding = "8bit"
    mail.deliver
  end
  
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  
  def send_password_reset_email
    mail = UserMailer.password_reset(self)
    mail.transport_encoding = "8bit"
    mail.deliver
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  private
    def downcase_email
      self.email = email.downcase
    end
    
    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/acount_activations_controller.rb
class AcountActivationsController < ApplicationController
  
  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in(user)
      flash[:succes] = "メールアドレスを確認致しました"
      redirect_to user
    else
      flash[:danger] = "メールアドレスの認証に失敗しました"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  def new
  end
  
  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "パスワード再設定のメールを送信しました"
      redirect_to root_url
    else
      flash.now[:danger] = "メールアドレスが登録されていません"
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "パスワードは必須です")
      render 'edit'
    elsif @user.update_attribute(user_params)
      log_in @user
      flash[:succes] = "パスワードを再設定しました"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  
    def get_user
      @user = User.find_by(email: params[:email])
    end
    
    def valid_user
      unless @user && @user.activated? && @user.authenticated?(:reset, params[:id])
        redirect_to root_url
      end
    end
    
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "パスワード再設定リンクの有効期間が切れています"
        redirect_to new_password_reset_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        flash[:success] = "ログインしました"
        redirect_to user
      else
        message = "メールアドレスの確認が取れていません"
        message += "登録時に送信されたメールから認証を済ませてください"
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash[:danger] = "メールアドレスとパスワードの組み合わせが正しくありません"
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :mine_user, only: [:edit, :update, :destroy]
  before_action :wing_user, only: [:wing, :show]
  
  def top
  end
 
  def index
    @users = User.where(open: true, activated: true).paginate(page: params[:page], per_page: 20).order(created_at: :DESC)
  end
  
  def wing
    @users = User.paginate(page: params[:page], per_page:20)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    if logged_in? && !admin_user?
      redirect_to root_url
      flash[:danger] = "既にユーザー登録されています"
    end
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.open == '1' ? 'true' : 'false'
      @user.update_attributes(open: @user.open)
      @user.send_activation_email
      flash[:info] = "ご登録頂いたアドレスにメールを送りましたので認証を行ってください"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:succes] = "更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    @user.delete
    redirect_to root_url
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :tel, :budger, :station, :walk, :area, :year_built, :elevator, :floor, :pet, :season, :open, :other)
    end
    
    def set_user
      @user = User.find(params[:id])
    end
    
    def mine_user
      unless current_user == set_user || admin_user?
       redirect_to root_url
       flash[:danger] = "要求されたページへのアクセス権限がありません"
      end
    end
    
    def wing_user
      unless current_user.wing? || admin_user? || current_user == set_user
        redirect_to root_url
        flash[:danger] = "要求されたページへのアクセス権限がありません"
      end
    end  
end

app/helpers/acount_activations_helper.rb
module AcountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def admin_user?
    current_user.admin? if logged_in?
  end
  
  def wing_user?
    current_user.wing? || admin_user? if logged_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="col-md-12">
  株式会社ウイングコーポレーション　０８００－１７０－８８６６
</div>

app/views/layouts/_header.html.erb
<h1>マンションリクエスト</h1>

<nav class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
      <span class="sr-only">メニュー</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  
  <div id="gnavi" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "TOP", root_url %></li>
      <li><%= link_to "希望条件登録", new_user_path %></li>
      <li><%= link_to "公開されている情報一覧", users_path %></li>
      <li><%= link_to "ウイングホームページ", "http://www.w-ing.net/", target: "_blank" %></li>
      <% unless logged_in? %>
        <li><%= link_to "ログイン", login_path %></li>
      <% end %>  
      <% if logged_in? %>
        <li><%= link_to "自分のページを見る", user_path(current_user) %></li>
        <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
      <% end %> 
      <% if logged_in? && wing_user? %>
        <li><%= link_to "ウイング用ページ", users_wing_path %></li>
      <% end %>  
    </ul>
  </div>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>中古マンション希望リクエスト</title>
  <meta name="viewport" content="width=device-width">
  <meta name="description" content="横浜の中古マンション専門不動産ウイングコーポレーションが、お客様の希望条件で中古マンションを探すサイト。横浜及び神奈川で中古マンションを探している方、
  売却を考えている方は是非ご覧下さい" >
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <header>
        <%= render 'layouts/header' %>
      </header>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </div>
</body>
</html>

app/views/password_resets/edit.html.erb
  <div class="col-md-6 col-md-offset-3">
   <h1>パスワード再設定</h1> 
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render partial: 'shared/errors', locals: { model: @user} %>
      <%= hidden_field_tag :email, @user.email %>
      
      <%= f.label :password, "新しく設定するパスワード" %>
      <%= f.password_field :password, class: "form-control" %>
      
      <%= f.label :password_confirmation, "確認用パスワード再入力" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      
      <%= f.submit "送信", class: "btn btn-primary" %>
    <% end %>  
  </div>

app/views/password_resets/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>パスワード再設定</h1>
  
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.submit "送信", class: "btn btn-primary" %>
    <% end %>  
</div>

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= "#{model.errors.count}個のエラー" %></h2>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>  
    </ul>
  </div>
<% end %>  

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render partial: 'shared/errors', locals: { model: @user} %>

  <%= f.label :name, "氏名（必須）" %>
  <%= f.text_field :name, class: "form-control long" %>
  
  <%= f.label :email, "メールアドレス（必須）" %>
  <%= f.email_field :email, class: "form-control long" %>
  
  <%= f.label :password, "パスワード（必須　6文字以上）" %>
  <%= f.password_field :password, class: "form-control long" %>
  
  <%= f.label :password_confirmation, "パスワード再入力" %>
  <%= f.password_field :password_confirmation, class: "form-control long" %>
  
  <%= f.label :tel, "電話番号" %>
  <%= f.telephone_field :tel, class: "form-control long" %>
  
  <%= f.label :station, "希望最寄駅 (複数の場合はスペースで区切って記入してください)" %>
  <%= f.text_field :station, class: "form-control long" %>
  
  <p><%= f.label :budger, "予算" %><br>
  <%= f.select :budger, ['特に決めていない', 'リフォーム込み1000万円以下', 'リフォーム別1000万円以下', 'リフォーム込み1500万円以下', 'リフォーム別1500万円以下',
                         'リフォーム込み2000万円以下', 'リフォーム別2000万円以下', 'リフォーム込み2500万円以下', 'リフォーム別2500万円以下', 'リフォーム込み3000万円以下', 
                         'リフォーム別3000万円以下', '3000万円以上'], {:include_blank => '選択してください'}, class: "long" %></p>
  
  <p><%= f.label :walk, "駅からの距離" %><br>
  <%= f.select :walk, ['徒歩5分以内', '徒歩10分以内', '徒歩15分以内', 'バス便でも可'], {:include_blank => '選択してください'}, class: "long" %></p>
  
  <p><%= f.label :area, "希望専有面積" %><br>
  <%= f.select :area, ['狭くても可', '50㎡以上', '60㎡以上', '70㎡以上'], {:include_blank => '選択してください'}, class: "long" %></p>
  
  <p><%= f.label :year_built, "希望築年数" %><br>
  <%= f.select :year_built, ['築10年以内', '築20年以内', '築30年以内', '築40年以内', '古くても構わない'], {:include_blank => '選択してください'}, class: "long" %></p>
  
  <p><%= f.label :elevator, "エレベーターの有無" %><br>
  <%= f.select :elevator, ['必須', 'あれば良いが必須条件では無い', '無くても良い'], {:include_blank => '選択してください'}, class: "long" %></p>
  
  <p><%= f.label :floor, "エレベーター無し物件の場合、何階まで可能" %><br>
  <%= f.select :floor, ['1階', '2階', '3階', '4階', '5階'], {:include_blank => '選択してください'}, class: "long" %></p>
  
  <p><%= f.label :pet, "ペット飼育" %><br>
  <%= f.select :pet, ['必須', 'どっちでも良い', '飼えないマンションが良い'], {:include_blank => '選択してください'}, class: "long" %></p>
  
  <p><%= f.label :season, "購入希望時期" %><br>
  <%= f.select :season, ['出来るだけ早く', '3ヶ月以内', '半年以内', 'まだ具体的に決まっていない'], {:include_blank => '選択してください'}, class: "long" %></p>
  
  <p><%= f.label :other, "具体的希望" %><br>
  <%= f.text_area :other, class: "area" %></p>
  
  <p><%= f.label :open, "一般公開する" %>
  <%= f.check_box :open %><br>
  希望条件のみ公開で個人情報は公開されません<br>
  具体的希望は公開されますので、個人情報を書き込んだ場合は一般公開しないでください</p>
  
  <%= f.submit "送信", class: "btn btn-primary" %>

<% end %>

app/views/users/edit.html.erb
<div class="new-form">
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="user-index">
 
<%= will_paginate @users %>
　<table border=1>
    <tr><th>希望駅</th><th>駅からの距離</th><th>希望面積</th><th>築年数</th><th>エレベーター</th><th>希望階（エレ無し時）</th>
    <th>ペット飼育</th><th>予算</th><th>購入希望時期</th><th style="width:28%;">具体的希望</th></tr>　
  <% @users.each do |user| %>
      <tr><td><%= user.station %></td><td><%= user.walk %></td><td><%= user.area %></td><td><%= user.year_built %></td><td><%= user.elevator %></td><td><%= user.floor %></td>
      <td><%= user.pet %></td><td><%= user.budger %></td><td><%= user.season %></td><td style="width: 28%;"><%= simple_format(user.other) %>
      <% if logged_in? && admin_user? || user == current_user %>
        <%= link_to "詳細", user_path(user), class: "btn btn-info btn-sm" %></td></tr>
      <% end %>  
  <% end %>
  </table>
<%= will_paginate @users %>  
</div>

app/views/users/new.html.erb
<div class="new-form">
  <%= render 'form' %>
  <P>登録後メールアドレス有効確認の為、メールを送らせて頂きます</P>
  <p>メール記載の確認用URLをクリックして登録を完了させてください</p>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="panel panel-default">
    <div class="panel-heading"><%= @user.name %></div>
    <ul class="list-group">
      <li class="list-group-item"><%= @user.email %></li>
      <li class="list-group-item"><%= @user.tel %></li>
      <li class="list-group-item">希望駅：<%= @user.station %></li>
      <li class="list-group-item">予算：<%= @user.budger %></li>
      <li class="list-group-item">駅からの距離：<%= @user.walk %></li>
      <li class="list-group-item">希望専有面積：<%= @user.area %></li>
      <li class="list-group-item">希望築年数：<%= @user.year_built %></li>
      <li class="list-group-item">エレベーターの有無：<%= @user.elevator %></li>
      <li class="list-group-item">エレベーター無しの場合場合の許容階数：<%= @user.floor %></li>
      <li class="list-group-item">ペット飼育：<%= @user.pet %></li>
      <li class="list-group-item">購入希望時期：<%= @user.season %></li>
      <li class="list-group-item">具体的希望：<%= simple_format(@user.other) %></li>
      <li class="list-group-item">
      <% if @user.open %>
        一般公開する
      <% else %>
        一般公開しない
      <% end %></li>
    </ul>
  </div>
  <% if @user == current_user || admin_user? %>
  <P>登録日： <%= "#{@user.created_at.to_s[0..3]}年#{@user.created_at.to_s[5..6]}月#{@user.created_at.to_s[8..9]}日" %></P>
  <p><%= link_to "修正する", edit_user_path(@user), class: "btn btn-primary" %>
    <%= link_to "削除する", user_path(@user), method: :delete, data: {confirm: "削除して宜しいですか？"}, class: "btn btn-primary" %></p>
  <% end %>  
</div>

app/views/users/top.html.erb
<div class="top">
  <h3>自己資金10万円で中古マンションを購入したいが、現在の販売中物件に希望が無い方</h3>
  <h3>物件探しを行っているが中々希望の物件が見つからない方</h3>
  <h3>中古マンションを購入して自分の希望のリフォームをしたい方</h3>
  <h1>ご希望条件を登録してください!!</h1>
  <p>こちらは、メールマガジンとは別でご登録頂きましたお客様の物件を探してご連絡致します</p>
  <p>ウイングには、仲介業者様からの紹介や一般売主様からの売却相談が毎日多数寄せられております</p>
  <p>しかしながら、弊社の在庫販売物件として購入する為には色々と経費もかかる為、金額合意が出来ないケースも御座います</p>
  <p>そういった物件の中にご登録頂いている方の希望に合うものがあれば、ご紹介させて頂きます</p>
  <p>そのうえで、弊社で一度買取り、リフォームをしてから販売させて頂く事も可能です</p>
  <p>この場合は、弊社販売中物件と同じように自己資金10万円で購入して頂く事が出来ます</p>
  <p>また、リフォームの際に弊社標準仕様リフォームプランと、希望リノベーションプランをお選び頂く事が出来ます</p>
  <p>希望リノベーションプランでは、標準仕様リフォームプランより高額となりますが、間取りや設備など</p>
  <p>ご自分のライフスタイルに合わせてお決め頂く事が可能です</p>
  <p>詳細については<%= link_to "希望リノベーションプラン", "http://www.w-ing.net/?page_id=6845", target: "_blank" %>のページをご覧ください</p>
  <p style="font-size: 2em; font-weight: bold; margin-top: 30px;"><<ご希望を登録して頂くにあたって>></p>
  <p>ご登録頂く際に、一般公開するかを選択出来ます</p>
  <p>一般公開した場合、希望条件がこちらのサイトに公開されます</p>
  <p>このページは仲介業者様や、物件売却を考えられている方も多く見られていますので、可能であれば公開してください</p>
  
  <h3>マンションのご売却をお考えの方、物件のご紹介を頂く方へ</h3>
  <p>公開されている情報一覧は、弊社にてリクエストを頂いているお客様の一部です</p>
  <p>大勢のお客様が、常に物件情報を待っている状態です</p>
  <h1>ご連絡お願いします!!</h1>
</div>

app/views/users/wing.html.erb
<%= will_paginate @users %>
　<table border=1>
    <tr><th>希望駅</th><th>駅からの距離</th><th>希望面積</th><th>築年数</th><th>エレベーター</th><th>希望階（エレ無し時）</th>
    <th>ペット飼育</th><th>予算</th><th>購入希望時期</th><th style="width:28%;">具体的希望</th></tr>　
  <% @users.each do |user| %>
      <tr><td><%= user.station %></td><td><%= user.walk %></td><td><%= user.area %></td><td><%= user.year_built %></td><td><%= user.elevator %></td><td><%= user.floor %></td>
      <td><%= user.pet %></td><td><%= user.budger %></td><td><%= user.season %></td><td style="width: 28%;"><%= simple_format(user.other) %>
        <%= link_to "詳細", user_path(user), class: "btn btn-info btn-sm" %>
        <% unless user.open %>
        <span>非公開</span></td></tr>
        <% end %>
  <% end %>
  </table>
<%= will_paginate @users %>  